---
- include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_os_family }}.yml"

- name: add 32bit architecture
  become: true
  shell: dpkg --add-architecture i386 && apt-get update
  when: ansible_distribution == "Ubuntu"

- name: install dependent packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ klocwork_dep_packages }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ klocwork_user }}"
  with_items: "{{ klocwork_create_dirs }}"

- name: change NOFILE limit
  pam_limits:
    domain: "{{ klocwork_user }}"
    limit_item: nofile
    limit_type: "-"
    value: 2048
    use_max: yes

- name: create klocwork user
  user:
    name: "{{ klocwork_user }}"

- name: check klocwork installed
  stat:
    path: "{{ klocwork_dir }}/bin/kwservice"
  register: kws_stat

- name: set klocwork installed facts
  set_fact:
    klocwork_install_required: "{{ kws_stat.stat.exists == False }}"
    klocwork_installer_path: "{{ klocwork_installer_dest }}/kw-server-installer.sh"

- name: copy klocwork installer
  copy:
    src: "{{ klocwork_installer_src }}"
    dest: "{{ klocwork_installer_path }}"
    mode: "755"
  when: klocwork_install_required

- name: install klocwork
  become: true
  become_user: "{{ klocwork_user }}"
  shell: "{{ klocwork_installer_path }} -a --klocwork-port {{ klocwork_port_web }} --license-port {{ klocwork_port_license }} --database-port {{ klocwork_port_database }} {{ klocwork_dir }}"
  when: klocwork_install_required

- name: copy klocwork license
  become: true
  become_user: "{{ klocwork_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ klocwork_dir }}/projects_root/licenses/"
  with_fileglob:
  - "{{ klocwork_license_file }}"

- name: copy klocwork clients
  become: true
  become_user: "{{ klocwork_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ klocwork_dir }}/clients/"
  with_fileglob:
  - "{{ klocwork_desktop_tools_files }}"

- name: create klocwork start/stop script
  template:
    src: "{{ item }}"
    dest: "{{ klocwork_script_dir }}/{{ item | basename | regex_replace('\\.j2', '') }}"
    owner: "{{ klocwork_user }}"
    mode: "755"
  with_items:
  - kwstart.sh.j2
  - kwstop.sh.j2

- name: start klocwork service
  become: true
  become_user: "{{ klocwork_user }}" 
  shell: nohup ./kwstart.sh > /dev/null 2> /dev/null < /dev/null
  args:
    chdir: "~{{ klocwork_user }}"
  when: klocwork_start_service

- name: remove klocwork installer
  file:
    path: "{{ klocwork_installer_path }}"
    state: absent
