---
- include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_os_family }}.yml"

- include_tasks: install.yml
  when: klocwork_state == 'present'

- include_tasks: uninstall.yml
  when: klocwork_state == 'absent'
